apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otelcol
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-targetallocator-sa
    prometheusCR:
      enabled: true
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 30s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]
        target_allocator:
          endpoint: http://otelcol-targetallocator
          interval: 30s
          collector_id: "${POD_NAME}"

      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - http://*
                - https://*
    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024
    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: tempo-prod-10-prod-eu-west-2.grafana.net:443
        headers:
          authorization: Basic OTY0NDM4OmdsY19leUp2SWpvaU1URTVOelEyTXlJc0ltNGlPaUp6ZEdGamF5MHhNREV5TXpRekxXaHNMWGR5YVhSbExXUnZhemh6SWl3aWF5STZJazVSU0RWM2VUUk5OVWszTjNSM1FsbzJaVEl3UnpVd1RpSXNJbTBpT25zaWNpSTZJbkJ5YjJRdFpYVXRkMlZ6ZEMweUluMTk=
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlp]
          processors: [batch]
