kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: lavinmq-storage
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: lavinmq-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lavinmq-storage
  local:
    path: /mnt/lavinmq
    type: DirectoryOrCreate
