apiVersion: v1
kind: Service
metadata:
  name: lavinmq-sample-lb
spec:
  type: LoadBalancer
  selector:
    app: lavinmq-sample
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: mgmt
      port: 15672
      targetPort: 15672
      protocol: TCP
