apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-test
  labels:
    app: otel-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otel-test
  template:
    metadata:
      labels:
        app: otel-test
    spec:
      containers:
        - name: otel-test
          image: otel-test:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otelcol-collector:4317"
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: otel-test
  labels:
    app: otel-test
spec:
  type: LoadBalancer
  selector:
    app: otel-test
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
