apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-worker
  labels:
    app: random-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: random-worker
  template:
    metadata:
      labels:
        app: random-worker
    spec:
      containers:
        - name: random-worker
          image: random-worker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: SERVICE_NAME
              value: "random-worker"
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
            - name: OTEL_COLLECTOR_URL
              value: "http://otelcol-collector-headless:4318/v1/traces"
            - name: AMQP_URL
              value: "amqp://default_user_jv9GUd8KvfaqOisBq5z:AFDTEkFFd17Aav9D6simibY9a9_Fzuwo@rabbitmq-cluster.default.svc:5672"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: random-worker
  labels:
    app: random-worker
spec:
  type: LoadBalancer
  selector:
    app: random-worker
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
