apiVersion: apps/v1
kind: Deployment
metadata:
  name: apip
  labels:
    app: apip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apip
  template:
    metadata:
      labels:
        app: apip
    spec:
      containers:
        - name: apip
          image: apip:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: SERVICE_NAME
              value: "apip"
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
            - name: OTEL_COLLECTOR_URL
              value: "http://otelcol-collector-headless:4318"
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: apip
  labels:
    app: apip
spec:
  type: LoadBalancer
  selector:
    app: apip
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
